#!/bin/bash

hostname=$(hostname -a)
if [ "$hostname" != "shoots" ]
then
  echo "You should not be running this here"
  exit
fi

#rsync -av --no-perms /var/www/sites/telamenta-drupal6/sites/p2pu.org/ anton@69.164.208.57:/var/www/p2pu/sites/p2pu.org/
rsync -avc --no-times --no-perms /var/www/sites/telamenta-drupal6/sites/p2pu.org/modules/ anton@69.164.208.57:/var/www/p2pu/sites/p2pu.org/modules/
rsync -avc --no-times --no-perms /var/www/sites/telamenta-drupal6/sites/p2pu.org/themes/ anton@69.164.208.57:/var/www/p2pu/sites/p2pu.org/themes/
