<?php
// $Id:



/* ----- Hook implementation ---- */



/**
 * Implementation of hook_perm
 */
function popup_perm(){
  return array(
    'administer popup elements',
  );
}



/**
 * Implementation of hook_menu
 */
function popup_menu(){

  return array(

    'admin/settings/popup' => array(
      'access arguments' => array('administer popup elements'),
      'page arguments' => array('popup_admin_settings'),
      'page callback' => 'drupal_get_form',
      'title' => 'Popup elements',
      'type' => MENU_NORMAL_ITEM,
    ),

  );
}



/**
 * Implementation of hook_preprocess
 */
function popup_preprocess(){

  $path = drupal_get_path('module', 'popup');
  $style_path = variable_get('popup-style', drupal_get_path('module', 'popup').'/styles/Default');

  drupal_add_css($path.'/popup.css', 'module', 'screen', variable_get('popup-preprocess', FALSE));

  static $script_added = FALSE;

  if (!$script_added){
	  drupal_add_js(array(
      'popup' => array(
        'hoverLinger' => variable_get('popup-hover-linger', 250)
      )
    ), 'setting', 'header', FALSE, FALSE, variable_get('popup-preprocess', FALSE));
    drupal_add_js($path.'/popup.js', 'module', 'header', FALSE, FALSE, variable_get('popup-preprocess', FALSE));
    $script_added = true;
  }

	if ($style_path){
	  drupal_add_css($style_path.'/popup-style.css', 'module', 'screen', variable_get('popup-preprocess', FALSE));
	}
}



/**
 * Implementation of hook_footer
 */
function popup_footer(){
  // Help the ugly sisters render position correctly
  return '<!--[if lt IE 8]><style type="text/css">div.popup-element{ display: inline;}</style><![endif]-->';
}



/**
 * Implementation of hook_theme
 */
function popup_theme(){
  return
    array(

      'popup_element' => array(
        'arguments' => array('element' => ''),
      ),

      'popup_element_title' => array(
        'arguments' => array('title' => 'no title'),
      ),

      'popup_element_body' => array(
        'arguments' => array('body' => ''),
      ),

    );
}



/**
 * Implementation of hook_popup_styles
 *
 */
function popup_popup_styles(){


  $path = drupal_get_path('module', 'popup');
  $style_dir = opendir($path.'/styles');

  while ($style_path = readdir($style_dir)){

    if (is_dir($path.'/styles/'.$style_path) && $style_path != '.' && $style_path != '..'){
      $styles[$path.'/styles/'.$style_path] = $style_path;
    }

  }

  closedir($style_dir);

  return $styles;
}



/**
 * Implementation of hook_form_alter
 *
 * Hooked to keep track of forms available to the system
 *
 * @param unknown_type $form
 * @param unknown_type $form_state
 * @param unknown_type $form_id
 */
function popup_form_alter(&$form, &$form_state, $form_id){

  static $form_registry = FALSE;

  if (!$form_registry){
    $form_registry = variable_get('form-registry', array());
  }

  if (!$form_registry[$form_id]){
    $form_registry[$form_id] = $form_id;
    variable_set('form-registry', $form_registry);
  }

}



/* ---- Forms ---- */



function popup_admin_settings(){

  $form = array();

  $style_options = module_invoke_all('popup_styles');

  $form['popup-style'] = array(
    '#default_value' => variable_get('popup-style', drupal_get_path('module', 'popup').'/styles/Default'),
    '#description' => 'Select the style in which to display popups.',
    '#options' => $style_options,
    '#title' => 'Popup style',
    '#type' => 'select',
  );

  $form['popup-hover-linger'] = array(
    '#default_value' => variable_get('popup-hover-linger', 250),
    '#description' => 'Select the amount of time in ms that hover popups should linger before closing.',
    '#options' => array(250 => 250, 500 => 500, 750 => 750, 1000 => 1000, 1250 => 1250, 1500 =>1500, 1750 => 1750, 2000 => 2000),
    '#title' => 'Hover linger',
    '#type' => 'select',
  );

  $form['popup-preprocess'] = array(
    '#default_value' => variable_get('popup-preprocess', FALSE),
    '#description' => 'Allow performance optimization to be performed on the popup CSS and Javascript. Disable this option if popup styles are not working.',
    '#title' => 'Optimize',
    '#type' => 'checkbox',
  );

  return system_settings_form($form);
}



/* ----- Theme implementation ---- */



function theme_popup_element($element){
  return $element;
}



function theme_popup_element_title($title){
  return '<span>'.$title.'</span>';
}



function theme_popup_element_body($body){
  return $body;
}


