<?php

/**
 * Implementation of hook_menu().
 */
function menu_editor_menu() {
  $items['admin/build/menu-customize/%menu/poweredit'] = array(
    'title' => 'Power Edit',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('menu_editor_overview_form', 3),
    // 'title callback' => 'menu_editor_overview_title',
    // 'title arguments' => array(3),
    'access arguments' => array('administer menu'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'menu_editor.admin.inc',
  );

  return $items;
}

function menu_editor_admin_menu() {
  $result = db_query("SELECT * FROM {menu_custom} ORDER BY title");
  $items = array();
  while ($menu = db_fetch_array($result)) {
    $items[] = array(
      'title' => $menu['title'],
      'path' => 'admin/build/menu-customize/'. $menu['menu_name'] . '/poweredit',
      'parent_path' => 'admin/build/menu/list',
      'weight' => 100,
    );
  }
  return $items;
}

/**
 * Implemenation of hook_theme().
 */
function menu_editor_theme() {
  return array(
    'menu_editor_overview_form' => array(
      'file' => 'menu_editor.admin.inc',
      'arguments' => array('form' => NULL),
    ),
  );
}

/**
 * Title callback for the menu overview page and links.
 */
function menu_editor_overview_title($menu) {
  return $menu['title'];
}
