<?php
// $Id: r4032login.install,v 1.1.4.3 2009/07/13 15:14:18 deekayen Exp $

/**
 * Implementation of hook_enable().
 */
function r4032login_enable() {
  variable_set('site_403', 'r4032login');
}

/**
 * Implementation of hook_disable().
 */
function r4032login_disable() {
  variable_del('site_403');
}

/**
 * Implementation of hook_uninstall().
 */
function r4032login_uninstall() {
  variable_del('r4032login_display_denied_message');
  variable_del('r4032login_user_register_message');
}
